[package]
name = "home_cron"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-coap = { git = "https://github.com/google/rust-async-coap.git", ref = "71245d4" }
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.10"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"
socket2 = "0.4"
futures = "0.3"
